blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),

]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('newsletter.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path
from newsletter.views import mailingListView,                             \
                            mailingDetailView, \
                            mailingUpdateView, \
                            mailingDeleteView, \
                            mailingCreateView, \
                            send_mailing, \
                            CustomerCreateView, \
                            CustomerListView, \
                            MailingLogListView
app_name = 'newsletter'  # Пространство имен для приложения "newsletter"

urlpatterns = [
    path('', mailingListView.as_view(), name='index'),
    path('newsletter/<int:pk>/', mailingDetailView.as_view(), name='mailing_detail'),
    path('create/', mailingCreateView.as_view(), name='mailing_create'),
    path('edit/<int:pk>/', mailingUpdateView.as_view(), name='mailing_update'),
    path('delete/<int:pk>', mailingDeleteView.as_view(), name='mailing_delete'),
    path('send_mailing/<int:mailing_id>/', send_mailing, name='send_mailing'),
    path('create_customer/', CustomerCreateView.as_view(), name='create_customer'),
    path('customer_list/', CustomerListView.as_view(), name='customer_list'),
    path('mailing_logs/', MailingLogListView.as_view(), name='mailing_log_list'),
]

newsletter/models.py
from django.db import models
from django.db import models
from django.conf import settings
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Customer(models.Model):
    """
    Клиент сервиса:
        контактный email,
        ФИО,
        комментарий.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE)
    email = models.EmailField(max_length=255, unique=True, verbose_name='Почта')
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    middle_name = models.CharField(max_length=50, **NULLABLE, verbose_name='Отчество')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Mailing(models.Model):
    FREQUENCY_CHOICES = (
        ('daily', 'Раз в день'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
    )

    STATUS_CHOICES = (
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('completed', 'Завершена'),
    )

    mailing_datetime = models.DateTimeField(auto_now_add=True, verbose_name='Время и дата рассылки')
    frequency = models.CharField(max_length=10, choices=FREQUENCY_CHOICES, verbose_name='Периодичность')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='created', verbose_name='Статус рассылки')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Создатель', related_name='mailings')
    clients = models.ManyToManyField('Customer', related_name='mailings', verbose_name='Клиенты')
    message = models.ForeignKey('MailText', on_delete=models.CASCADE, verbose_name='Сообщение', **NULLABLE)

    def __str__(self):
        return f"Рассылка ({self.frequency})"


class MailText(models.Model):
    """
    Сообщение для рассылки:
        тема письма,
        тело письма.
    """
    topic = models.CharField(max_length=100, verbose_name='Тема рассылки', unique=True)  # Добавлено unique=True
    message = models.TextField(verbose_name='Текст сообщения')

    def __str__(self):
        return self.topic


class MailingLog(models.Model):
    STATUS_CHOICES = (
        ('success', 'Успех'),
        ('failure', 'Ошибка'),
    )

    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, verbose_name='Статус попытки')
    server_response = models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, related_name='mailing_logs')

    def __str__(self):
        return f"{self.timestamp}, Статус: {self.status})"

newsletter/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic import CreateView, ListView, DetailView, CreateView, UpdateView, TemplateView, DeleteView
from newsletter.models import Customer, Mailing, MailText, MailingLog
from django.urls import reverse_lazy, reverse
from newsletter.mailing_forms import MailingForm, MailTextForm, CustomerForm
from django.forms import inlineformset_factory, modelformset_factory
from django.core.mail import send_mail
from django.http import HttpResponse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.models import Permission
from django.shortcuts import redirect
from django.contrib.auth import get_user_model
from django.contrib.auth import logout
from random import sample
from blog.models import Blog


class mailingCreateView(CreateView):
    """
        Класс для создания новой рассылки.
    """

    model = Mailing
    template_name = 'newsletter/mailing_form.html'
    form_class = MailingForm
    success_url = reverse_lazy('newsletter:index')

    extra_context = {
        'title': 'Создать рассылку',
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        CustomerFormset = modelformset_factory(MailText, form=MailTextForm, extra=1)

        if self.request.method == 'POST':
            context_data['formset'] = CustomerFormset(self.request.POST)
        else:
            context_data['formset'] = CustomerFormset(queryset=Customer.objects.none())

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        form.instance.creator = self.request.user

        self.object = form.save()

        if formset.is_valid():
            for customer_form in formset:
                if customer_form.cleaned_data:
                    customer = customer_form.save(commit=False)
                    customer.mailing_list = self.object
                    customer.save()

        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['clients'].queryset = self.request.user.customer_set.all()
        return form


class mailingListView(ListView):
    """
    Класс для просмотра списка рассылок.
    """
    template_name = 'newsletter/index.html'
    context_object_name = 'newsletter_list'

    extra_context = {
        'title': 'Список рассылок',
    }

    @method_decorator(login_required(login_url=reverse_lazy('users:login')), name='dispatch')
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if user.is_blocked:
            logout(request)
            return render(request, 'users/blocked_user.html')  # Вызываем шаблон
        else:
            return super().get(request, *args, **kwargs)

    def get_queryset(self):
        if self.request.user.is_staff:
            return Mailing.objects.all()
        else:
            return Mailing.objects.filter(creator_id=self.request.user.id).select_related('message', 'creator').prefetch_related('clients')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user
        unique_customers = set()

        if current_user.is_staff:
            all_users = get_user_model().objects.all()

            for user in all_users:
                newsletter_customers = Customer.objects.filter(user=user)
                for newsletter_customer in newsletter_customers:
                    unique_customers.add(newsletter_customer.email)
        else:
            newsletter_customers = Customer.objects.filter(user=current_user)

            for newsletter_customer in newsletter_customers:
                unique_customers.add(newsletter_customer.email)

        total_unique_customers = len(unique_customers)

        context['total_unique_customers'] = total_unique_customers

        # Добавляем подсчет активных рассылок
        if current_user.is_staff:
            # Если пользователь - админ, показываем все активные рассылки
            active_mailings_count = Mailing.objects.filter(status='started').count()
        else:
            # Если пользователь не админ, показываем только активные рассылки, созданные им
            active_mailings_count = Mailing.objects.filter(status='started', creator=current_user).count()

        context['active_mailings_count'] = active_mailings_count

        # Получаем случайные блоги
        if current_user.is_staff:
            # Если пользователь - суперпользователь, показываем три случайных блога всех пользователей
            random_blogs = Blog.objects.order_by('?')[:3]
        else:
            # Если пользователь не суперпользователь, показываем три случайных своих блога
            random_blogs = Blog.objects.filter(author=current_user).order_by('?')[:3]

        context['random_blogs'] = random_blogs

        return context


class mailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingForm

    success_url = reverse_lazy('newsletter:index')

    extra_context = {
        'title': 'Создать рассылку',
    }


class mailingDetailView(DeleteView):
    model = Mailing
    template_name = 'newsletter/mailing_detail.html'
    ontext_object_name = 'newsletter_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message_topic'] = self.object.message.topic  # Добавляем message_topic в контекст
        context['title'] = self.object.message.topic  # Задаем значение title
        return context


class mailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('newsletter:index')


class MailingLogListView(ListView):
    model = MailingLog
    template_name = 'newsletter/mailing_logs.html'  # Создайте шаблон для отображения списка логов
    context_object_name = 'mailing_logs'  # Имя переменной контекста в шаблоне
    extra_context = {
        'title': 'Логи рассылки',
    }


class CustomerCreateView(CreateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'newsletter/create_customer.html'
    success_url = reverse_lazy('newsletter:customer_list')
    extra_context = {
        'title': 'Создать клиента',
    }

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CustomerListView(ListView):
    model = Customer
    template_name = 'customer_list.html'
    context_object_name = 'customers'

    extra_context = {
        'title': 'Список клиентов',
    }

    def get_queryset(self):
        if self.request.user.is_staff:
            return Customer.objects.all()
        else:
            return Customer.objects.filter(user=self.request.user)



def send_mailing(request, mailing_id):
    mailing = Mailing.objects.get(pk=mailing_id)

    clients = mailing.clients.all()

    message_text = mailing.message.message

    mailing_logs = []

    for client in clients:
        subject = mailing.message.topic
        from_email = 'vitalik.karpukhin@list.ru'
        recipient_list = [client.email]

        try:
            send_mail(subject, message_text, from_email, recipient_list)
            status = 'success'
            server_response = 'Письмо успешно отправлено'
        except Exception as e:
            status = 'failure'
            server_response = str(e)

        mailing_log = MailingLog(mailing=mailing, status=status, server_response=server_response)
        mailing_logs.append(mailing_log)

    MailingLog.objects.bulk_create(mailing_logs)

    mailing.status = 'completed'
    mailing.save()
    return HttpResponse("Рассылка успешно отправлена")

newsletter/templates/newsletter/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
</head>
  <body>
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7">
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                {% if user.is_authenticated %}
                  <li><a href="{% url 'users:profile' %}">Профиль</a></li>
                  <li><a href="{% url 'blog:list' %}">Блог</a></li>
                  <li><a href="{% url 'users:logout' %}">Выйти</a></li>
                {% else %}
                   <li><a href="{% url 'users:login' %}">Войти</a></li>
                   <li><a href="{% url 'users:register' %}">Регистрация</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="{% url 'newsletter:index' %}" class="navbar-brand d-flex align-items-center">
            <strong>Главная</strong>
          </a>
          <div class="d-flex">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            </div>
        </div>

      </div>
    </div>
 </header>
<main role="main" style="position: relative; overflow: hidden;">
      <section class="text-center py-5">
        <div class="container">
          <h1 class="jumbotron-heading">{{ title|capfirst }}</h1>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
      </div>
    </main>
<footer class="text-muted">
    <div class="container">

    </div>
</footer>

 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script src="{% static 'js/holder.min.js'%}"></script>
</body>
</html>

newsletter/templates/newsletter/create_customer.html
{% extends 'newsletter/base.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="footer">
          <button type="submit" class="btn btn-primary mr-5">Создать</button>
          <a href="{% url 'newsletter:customer_list' %}" class="btn btn-secondary">К списку клиентов</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

newsletter/templates/newsletter/index.html
{% extends 'newsletter/base.html' %}
{% load static %}
{% block content %}

{% include 'newsletter/panel/info_panel.html' %}
{% if user.is_authenticated %}
{% include 'newsletter/panel/option_panel.html' %}

<div class="row">
<!--<p>Привет, {{ user.id }} {{ mailing.creator.id }}!</p>-->
    {% for mailing in newsletter_list %}
        <div class="col-md-6">
            <div class="card box-shadow mt-5">
                {% if user.is_superuser and user.id == mailing.creator.id %}
                     <div class="card-header" style="border: 1px solid #28a745">
                         <p><small class="text-success">Тема рассылки:</small> {{ mailing.message.topic | capfirst }} | <small class="text-danger">Вы являетесь собственником этой рассылки.</small></p>
                     </div>
                    {% else %}
                        <div class="card-header">
                         <p><small class="text-success">Тема рассылки:</small> {{ mailing.message.topic | capfirst }}</p>
                     </div>
                {% endif %}

                <div class="card-body">
                    <p><small class="text-success">Тема рассылки:</small> {{ mailing.message.message | capfirst | truncatechars:100 }}</p>
                    <hr>
                    <p><small class="text-success">Количество клиентов:</small> {{ mailing.clients.count }}</p>
                    <p>
                        <small class="text-success status">Статус рассылки:</small>
                        {% if mailing.status == 'created' %}
                            Создана
                        {% elif mailing.status == 'started' %}
                            Запущена
                        {% elif mailing.status == 'completed' %}
                            Завершена
                        {% else %}
                            Неизвестный статус
                        {% endif %}
                    </p>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-between align-items-center" style="width:300px">
                        <a href="{% url 'newsletter:mailing_detail' pk=mailing.pk %}" class="btn btn-primary mr-2">Смотреть</a>
                        {% if not user.is_staff %}
                            <a href="{% url 'newsletter:mailing_update' pk=mailing.pk %}" class="btn btn-success mr-2">Изменить</a>
                        {% endif %}
                        <a href="{% url 'newsletter:mailing_delete' pk=mailing.pk %}" class="btn btn-danger mr-2">Удалить</a>
                        <a href="{% url 'newsletter:send_mailing' mailing_id=mailing.pk %}" class="btn btn-warning">Отправить сейчас</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endif %}
<script src="{% static 'js/info_panel.js' %}"></script>
{% endblock %}

newsletter/templates/newsletter/mailing_confirm_delete.html
{% extends 'newsletter/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-12">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p class="">Хотите удалить рассылку "{{ mailing.message.topic }}"?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'newsletter:index' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

newsletter/templates/newsletter/mailing_detail.html
{% extends 'newsletter/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <p class="card-text"><strong>Тема рассылки:</strong> {{ mailing.message.topic }}</p>
            </div>
            <div class="card-body">
                <p class="card-text"><strong>Текст рассылки:</strong> {{ mailing.message.message }}</p>
                <p><strong>Количество клиентов:</strong> {{ mailing.clients.count }}</p>
                <strong>Клиенты:</strong>
                <ul>
                    {% for customer in mailing.clients.all %}
                    <li>{{ customer.email }} - {{ customer.first_name|capfirst }} {{ customer.last_name|capfirst }} {% if customer.middle_name|capfirst %}{{ customer.middle_name|capfirst }}{% endif %}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <div class="text-muted">Автор: {{ mailing.creator }}</div>
                        <div>
                            <small class="text-muted">{{ mailing.mailing_datetime }}</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/mailing_form.html
{% extends 'newsletter/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Настройки письма</h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                        {% if form.instance.pk %}
                            Изменить
                        {% else %}
                            Создать
                        {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

newsletter/templates/newsletter/mailing_logs.html
{% extends 'newsletter/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <a href="{% url 'newsletter:index' %}" class="btn btn-primary mr-2">На главную</a>
            <table class="table table-bordered mt-5">
                <thead>
                    <tr>
                        <th>Email</th>
                        <th>Дата и время попытки</th>
                        <th>Статус попытки</th>
                        <th>Частота</th>
                        <th>Ответ почтового сервера</th>
                    </tr>
                </thead>
                <tbody>
                    {% for log in mailing_logs %}
                        <tr>
                            <td>
                                {% for client in log.mailing.clients.all %}
                                    {{ client.email }}
                                    {% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </td>
                            <td>{{ log.timestamp }}</td>
                            <td>
                                {% if log.status == 'success' %}
                                    <span class="text-success">Успешно</span>
                                {% elif log.status == 'failure' %}
                                    <span class="text-danger">Ошибка</span>
                                {% else %}
                                    <span class="text-muted">Неизвестный статус</span>
                                {% endif %}
                            </td>
                            <td>
                                {% if log.mailing.frequency == 'daily' %}
                                    Раз в день
                                {% elif log.mailing.frequency == 'weekly' %}
                                    Раз в неделю
                                {% elif log.mailing.frequency == 'monthly' %}
                                    Раз в месяц
                                {% else %}
                                    Неизвестная периодичность
                                {% endif %}
                            </td>
                            <td>
                                {% if "user not found" in log.server_response %}
                                    Адрес электронной почты не существует
                                {% else %}
                                    {{ log.server_response }}
                                {% endif %}
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5">Нет доступных логов.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

newsletter/templates/newsletter/mailing_sent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Рассылка отправлена</title>
</head>
<body>
    <h1>Рассылка успешно отправлена</h1>
    <p>Ваше сообщение было успешно отправлено на указанные адреса электронной почты.</p>
    <a href="{% url 'index' %}" class="btn btn-primary">На главную</a>
</body>
</html>